apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MONGO_USERNAME: "kazbar2002_db_user"
  MONGO_PASSWORD: "r3h5FQAaXWOSoIZu"
  ACCESS_TOKEN: "decc69aca5047faa378a3dd83c051d7ac5c2ad863a9982be624bd72b900e0823"
